# Generated by Django 3.0.3 on 2021-01-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bucket',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
